#for reactjs ts project
from node:21-alpine as build
workdir /app
copy package*.json ./
run npm i
copy . .
run npm run build

from nginx:alpine 
workdir /app
copy --from=build /app/dist /usr/share/nginx/html
copy nginx.conf /etc/nginx/conf.d/default.conf

cmd ["nginx","-g","daemon off;"]